# Generated by Django 5.2 on 2025-05-03 19:43

import django.core.files.storage
import sidecar_openai.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sidecar_openai", "0004_alter_thread_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openaifile",
            name="file",
            field=models.FileField(
                max_length=512,
                storage=django.core.files.storage.FileSystemStorage(
                    "/tmp/openaifiles", base_url="/"
                ),
                upload_to=sidecar_openai.models.hashed_upload_to,
                validators=[sidecar_openai.models.validate_file_extension],
            ),
        ),
    ]
