# Generated by Django 5.2 on 2025-05-10 21:09

import django.core.files.storage
import sidecar_openai.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sidecar_openai", "0008_assistant_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="assistant",
            name="max_tokens",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assistant",
            name="temperature",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="openaifile",
            name="file",
            field=models.FileField(
                max_length=512,
                storage=django.core.files.storage.FileSystemStorage(
                    "/subdomain-data/query", base_url="/"
                ),
                upload_to=sidecar_openai.models.hashed_upload_to,
                validators=[sidecar_openai.models.validate_file_extension],
            ),
        ),
    ]
