# Generated by Django 5.2 on 2025-05-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sidecar_openai", "0012_alter_assistant_instructions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assistant",
            name="vector_stores",
            field=models.ManyToManyField(blank=True, to="sidecar_openai.vectorstore"),
        ),
    ]
