"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import psycopg2
from psycopg2.extensions import ISOLATION_LEVEL_AUTOCOMMIT



from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-j&#s2gvaj5fi6$4*=#8+o8_^&ohpap2b2=rm-so72-xrzx=_qo"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    "grappelli",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": ["backend/templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

#DATABASES = {
#    "default": {
#        "ENGINE": "django.db.backends.sqlite3",
#        "NAME": BASE_DIR / "db.sqlite3",
#    }
#}

PGDATABASE = os.environ.get('PGDATABASE')
PGDATABASE_NAME = os.environ.get('PGDATABASE_NAME','default')
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
SUBDOMAIN = os.environ.get('SUBDOMAIN','query')
ATOMIC_REQUESTS = False
PGHOST = os.environ.get("PGHOST", "localhost")
PGPASSWORD = os.environ.get("PGPASSWORD")
PGUSER = os.environ.get("PGUSER")
PGDATABASE = os.environ.get('PGDATABASE')
PGDATABASE_NAME = os.environ.get('PGDATABASE_NAME','default')


DJANGO_RAGAMUFFIN_DB = os.environ.get("DJANGO_RAGAMUFFIN_DB",None) 

DATABASES = {
     'default' : {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": PGDATABASE,
        "USER": PGUSER,
        "PASSWORD": PGPASSWORD,
        "HOST": PGHOST,
        "PORT": 5432,
        "ATOMIC_REQUESTS": ATOMIC_REQUESTS,
    },
    'django_ragamuffin': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': DJANGO_RAGAMUFFIN_DB,
        'USER': PGUSER,
        'PASSWORD': PGPASSWORD,
        'HOST': 'localhost',
        'PORT': '5432',
        'ATOMIC_REQUESTS' : ATOMIC_REQUESTS
    }
}

db = DATABASES[PGDATABASE_NAME];
db_name = db['NAME'];
host = db['HOST'];
user = db['USER'];
password = db['PASSWORD']
superuser = os.environ.get("SUPERUSER", 'super')
superuser_password = os.environ.get("SUPERUSER_PASSWORD",'')
SUPERUSER=superuser
SUPERUSER_PASSWORD=superuser_password
#create_database_if_not_exists(db_name, host,user, password , superuser, superuser_password) 








# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
import os
AI_KEY =  os.environ.get("OPENAI_API_KEY",None)
AI_MODEL = os.environ.get('AI_MODEL','gpt-5-mini')
OPENAI_UPLOAD_STORAGE =  os.environ.get("OPENAI_UPLOAD_STORAGE",'/tmp/openaifiles')
os.makedirs(OPENAI_UPLOAD_STORAGE, exist_ok=True)
INSTALLED_APPS.append('django_ragamuffin')
STATIC_ROOT = os.path.join(BASE_DIR, "deploystatic")
STATIC_URL = "deploystatic/"
MEDIA_URL = 'media/'
MEDIA_ROOT = OPENAI_UPLOAD_STORAGE

STATIC_URL = "/static/"
print(f"STORAGE = {OPENAI_UPLOAD_STORAGE}")
MAXWAIT = 120 ; # WAIT MAX 120 seconds
DEFAULT_TEMPERATURE = 0.2;
LAST_MESSAGES = 99
MAX_NUM_RESULTS = None
MAX_TOKENS = 8000 # NOT IMPLMENTED AS OF openai==1.173.0 
AI_MODELS = {'staff' : 'gpt-5-mini', 'default' : AI_MODEL }
API_APP = 'localhost'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field



LOGIN_URL = '/login'

AUTH_PASSWORD_VALIDATORS = [
    #{
    #    'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    #},
    # Remove or reduce the minimum length
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 4,
        }
    },
    # Comment out to allow common passwords
    #{
    #    'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    #},
    # Comment out to allow numeric passwords
    # {
    #     'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    # },
]
import sys

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,  # keeps default Django logs

    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'stream': sys.stdout,  # 👈 directs logs to stdout
        },
    },

    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },

    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'ERROR',  # or DEBUG/INFO depending on what you want
            'propagate': False,
        },
        # Your app-specific logger (optional)
        'django_ragamuffin': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
            },
    }
}

RUNTESTS = "pytest" in sys.modules
#if not RUNTESTS :
DATABASE_ROUTERS = ['django_ragamuffin.db_routers.RagamuffinRouter']
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "backend.settings")
#print(f"AI_MODELS= {AI_MODELS}")
#print(f"DATABASES = {DATABASES}")
print(f"AI_KEY = {AI_KEY}")
EFFORT = 'low'
AI_KEY =  os.environ.get("OPENAI_API_KEY",None)
AI_MODEL = os.environ.get('AI_MODEL','gpt-5')
AI_MODEL = 'gpt-5'
OPENAI_UPLOAD_STORAGE =  os.environ.get("OPENAI_UPLOAD_STORAGE",'/tmp/openaifiles')
os.makedirs(OPENAI_UPLOAD_STORAGE, exist_ok=True)
API_APP = 'localhost'
DJANGO_RAGAMUFFIN_DB = os.environ.get("DJANGO_RAGAMUFFIN_DB",None) 
d = settings.DATABASES['default'];
PGDATABASE = d['NAME'];
PGHOST = d['HOST']
PGUSER = d['USER'];
PGPASSWORD = d['PASSWORD']
#settings.DATABASES['django_ragamuffin'] =  {
#        'ENGINE': 'django.db.backends.postgresql',
#        'NAME': DJANGO_RAGAMUFFIN_DB,
#        'USER': PGUSER,
#        'PASSWORD': PGPASSWORD,
#        'HOST': 'localhost',
#        'PORT': '5432',
#        'ATOMIC_REQUESTS' : settings.ATOMIC_REQUESTS
#    }
if not hasattr(settings, 'SUBDOMAIN' ):
    SUBDOMAIN = os.environ.get('SUBDOMAIN','query')
MAXWAIT = 120 ; # WAIT MAX 120 seconds
DEFAULT_TEMPERATURE = 0.2;
LAST_MESSAGES = 99
MAX_NUM_RESULTS = None
MAX_TOKENS = 8000 # NOT IMPLMENTED AS OF openai==1.173.0 
AI_MODELS = {'staff' : 'gpt-5' , 'default' : AI_MODEL }
MEDIA_ROOT = OPENAI_UPLOAD_STORAGE
if not 'django_ragamuffin' in settings.LOGGING['loggers'] :
    settings.LOGGING['loggers']['django_ragamuffin'] = {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
            }


RUNTESTS = "pytest" in sys.modules
if not RUNTESTS :
    if not hasattr('settings','DATABASE_ROUTERS') :
        DATABASE_ROUTERS = ['django_ragamuffin.db_routers.RagamuffinRouter'] 
    else :
        DATABASE_ROUTERS = ['django_ragamuffin.db_routers.RagamuffinRouter'] + settings.DATABASE_ROUTERS

APP_KEY = os.environ.get('APP_KEY',None)
APP_ID = os.environ.get('APP_ID',None)
USE_MATHPIX = os.environ.get('USE_MATHPIX','False') == 'True'
if APP_KEY == None or APP_ID == None :
    USE_MATHPIX = False
DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
CHATGPT_TIMEOUT = 60
OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY')
AI_KEY =  OPENAI_API_KEY
USE_CHATGPT =  os.environ.get("USE_CHATGPT",False) == 'True'
DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
RUNTESTS = "pytest" in sys.modules

AI_KEY =  os.environ.get("AI_KEY",None)
USE_CHATGPT =  os.environ.get("USE_CHATGPT",False) == 'True'
#AI_MODEL = os.environ.get('AI_MODEL','gpt-3.5-turbo')
AI_MODEL = os.environ.get('AI_MODEL','gpt-4o-mini')
SERVER = os.environ.get("SERVER", OPENTA_SERVER )
DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
print(f"CACHES = {CACHES}")
APP_KEY = os.environ.get('APP_KEY',None)
APP_ID = os.environ.get('APP_ID',None)
USE_MATHPIX = os.environ.get('USE_MATHPIX','False') == 'True'
if APP_KEY == None or APP_ID == None :
    USE_MATHPIX = False
print(f"SESSION = {SESSION_ENGINE}")
DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
#NOCACHES = {};
#NOCACHES['default'] =  {
#        "BACKEND": "django.core.cache.backends.memcached.MemcachedCache",  # uses pure Python
#        "LOCATION": "memcached:11211",
#    }
#NOCACHES['default']  = {
#        'BACKEND': 'django.core.cache.backends.memcached.PyLibMCCache',
#        'LOCATION': 'memcached:11211',
#        'OPTIONS': {
#            'binary': True,
#            'behaviors': {
#                'tcp_nodelay': True,
#                'tcp_keepalive': True,
#                'connect_timeout': 2000,  # milliseconds
#                'send_timeout': 750 * 1000,
#                'receive_timeout': 750 * 1000,
#                'retry_timeout': 2,        # seconds before retrying downed server
#                'dead_timeout': 10,        # seconds to mark server as "dead"
#            },
#        },
#    }
CACHES['default']  = {
        "BACKEND": "django.core.cache.backends.memcached.PyMemcacheCache",
        "LOCATION": ["127.0.0.1:11211"],  # or "memcached:11211" in Docker/K8s
        "TIMEOUT": 300,  # Key TTL in seconds (None = never expire)
        "OPTIONS": {
            # Connection pooling
            "use_pooling": True,
            "max_pool_size": 10,

            # Network timeouts (in seconds)
            "connect_timeout": 2,   # TCP connection timeout
            "timeout": 2,           # Read/write timeout

            # TCP options
            "no_delay": True,       # Disable Nagle’s algorithm (faster small writes)
            #"tcp_keepalive": True,  # Keep connections alive

            # Error handling
            "ignore_exc": False,    # Raise errors instead of silently ignoring them
        },
    }


INSTALLED_APPS.append('django_ragamuffin')
DJANGO_RAGAMUFFIN_DB = os.environ.get("DJANGO_RAGAMUFFIN_DB",None) 
DATABASES.update({
    'django_ragamuffin': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': DJANGO_RAGAMUFFIN_DB,
        'USER': PGUSER,
        'PASSWORD': PGPASSWORD,
        'HOST': 'localhost',
        'PORT': '5432',
        'ATOMIC_REQUESTS' : False,
        }
    })

MAXWAIT = 120 ; # WAIT MAX 120 seconds
DEFAULT_TEMPERATURE = 0.2;
LAST_MESSAGES = 99
MAX_NUM_RESULTS = None
MAX_TOKENS = 8000 # NOT IMPLMENTED AS OF openai==1.173.0 
AI_MODELS = {'staff' : 'gpt-5-mini', 'default' : AI_MODEL }
API_APP = 'localhost'
EFFORT = 'low'
