# Generated by Django 5.2 on 2025-08-15 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_ragamuffin", "0035_alter_vectorstore_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyAssistant",
            fields=[
                (
                    "assistant_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="django_ragamuffin.assistant",
                    ),
                ),
            ],
            bases=("django_ragamuffin.assistant",),
        ),
        migrations.AlterField(
            model_name="thread",
            name="assistant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="threads",
                to="django_ragamuffin.myassistant",
            ),
        ),
    ]
