# Generated by Django 5.2 on 2025-08-15 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_ragamuffin", "0036_myassistant_alter_thread_assistant"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyThread",
            fields=[
                (
                    "thread_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="django_ragamuffin.thread",
                    ),
                ),
            ],
            bases=("django_ragamuffin.thread",),
        ),
    ]
