# Generated by Django 5.2 on 2025-08-21 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_ragamuffin", "0037_mythread"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assistant",
            name="vector_stores",
            field=models.ManyToManyField(
                blank=True,
                related_name="assistants",
                to="django_ragamuffin.vectorstore",
            ),
        ),
    ]
