kind: PersistentVolume
apiVersion: v1
metadata:
  name: ${SERVER_PREFIX}minikube-vol
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  storageClassName: pv-nvme-hostpath
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/pv-nvme/${SERVER_PREFIX}minikube-vol"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ${SERVER_PREFIX}minikube-pvc
spec:
  storageClassName: pv-nvme-hostpath
  accessModes:
    - ReadWriteOnce
  volumeName: ${SERVER_PREFIX}minikube-vol
  resources:
    requests:
      storage: 10Gi
---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: ${SERVER_PREFIX}deploystatic-vol
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  storageClassName: local-hostpath
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/pv/${SERVER_PREFIX}deploystatic-vol"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ${SERVER_PREFIX}deploystatic-pvc
spec:
  storageClassName: local-hostpath
  accessModes:
    - ReadWriteOnce
  volumeName: ${SERVER_PREFIX}deploystatic-vol
  resources:
    requests:
      storage: 1Gi

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: ${SERVER_PREFIX}subdomain-vol
  labels:
    type: local
spec:
  capacity:
    storage: 20Gi
  storageClassName: local-hostpath
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/pv/${SERVER_PREFIX}subdomain-vol"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ${SERVER_PREFIX}subdomain-pvc
spec:
  storageClassName: local-hostpath
  accessModes:
    - ReadWriteOnce
  volumeName: ${SERVER_PREFIX}subdomain-vol
  resources:
    requests:
      storage: 10Gi
