apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ${SUBDOMAIN}
  labels:
    app: ${SUBDOMAIN}
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  ${SUBDOMAIN}
  template:
    metadata:
      labels:
        app: ${SUBDOMAIN}
    spec:  
      volumes:
      - name: ${SERVER_PREFIX}subdomain-vol
        persistentVolumeClaim:
          claimName: ${SERVER_PREFIX}subdomain-pvc
      - name: ${SERVER_PREFIX}deploystatic-vol
        persistentVolumeClaim:
          claimName: ${SERVER_PREFIX}deploystatic-pvc

      containers:
        - name: ragamuffin
          image: 'opentaproject/ragamuffin:v20260824'
          imagePullPolicy: Always
          volumeMounts:
              - mountPath: "/subdomain-data"
                name: ${SERVER_PREFIX}subdomain-vol
              - mountPath: "/srv/django_ragamuffin/backend/deploystatic"
                name: ${SERVER_PREFIX}deploystatic-vol
    
          env: 
            - name: TZ
              value: "Europe/Stockholm" # Set your desired timezone
            - name: PGHOST
              value: "${SERVER_PREFIX}db-server"
            - name: NOT_PGHOST
              value: "${SERVER_PREFIX}pgbouncer-service"
            - name: DBHOST
              value: "${SERVER_PREFIX}db-server" # EDIT 
            - name: DEBUG
              value: 'True'
            - name:  SUBDOMAIN
              value: ${SUBDOMAIN}
            - name: OPENAI_API_KEY
              value: ${OPENAI_API_KEY}
            - name: APP_ID
              value: ${APP_ID}
            - name: APP_KEY
              value: ${APP_KEY}
            - name: SUPERUSER_PASSWORD
              value: ${SUPERUSER_PASSWORD}
            - name: PGPASSWORD
              value: ${PGPASSWORD}
            - name: PGUSER
              value: ${PGUSER}
            - name: SECRET_KEY
              value: ${SECRET_KEY}
            - name: SUPERUSER
              value: ${SUPERUSER}
            - name: PGDATABASE_NAME
              value: ${PGDATABASE_NAME}
            - name: LTI_KEY
              value: ${LTI_KEY}
            - name: LTI_SECRET
              value: ${LTI_SECRET}
            - name: PGDATABASE
              value: ${PGDATABASE}
            - name: HTTP_PROTOCOL
              value: "https"
            - name: HTTP_SERVER_PORT
              value: "443"
            - name: SCRAM_PASSWORD
              value: ${SCRAM_PASSWORD}
            - name: DJANGO_RAGAMUFFIN_DB
              value: ${DJANGO_RAGAMUFFIN_DB}

          command: ["/bin/bash","-c"]
          args: 
            - cd /srv/django_ragamuffin/backend;
              pip install -e /srv/django_ragamuffin/src;
              python manage.py collectstatic --no-input;
              /usr/bin/supervisord -c /srv/django_ragamuffin/backend/supervisord.conf 
              #npx @tailwindcss/cli -i static/css/input.css -o static/css/output.css;
              #python manage.py runserver

        - name: nginx
          image: 'opentaproject/ragamuffin-nginx:latest'
          imagePullPolicy: Always
          ports: 
            - containerPort: 8080
          volumeMounts:
            - mountPath: "/subdomain-data"
              name: ${SERVER_PREFIX}subdomain-vol
            - mountPath: "/deploystatic"
              name: ${SERVER_PREFIX}deploystatic-vol

    
---

kind: Service
apiVersion: v1
metadata:
  name: ${SUBDOMAIN}-service
spec:
  selector:
    app: ${SUBDOMAIN}
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8080
      name: http
